[package]
name = "bevy_oxr"
version = "0.1.0"
edition = "2021"
description = "Community crate for OpenXR in Bevy"
repository = "https://github.com/awtterpip/bevy_oxr"
license = "MIT/Apache-2.0"

[features]
default = ["linked", "vulkan"]
linked = ["openxr/linked"]
vulkan = ["dep:ash"]

[dependencies]
async-std = "1.12.0"
bevy = "0.12.1"
paste = "1.0.14"
wgpu = "0.17.1"
wgpu-hal = "0.17.1"
winit = "0.28.7"

[target.'cfg(target_family = "unix")'.dependencies]
openxr = { version = "0.17.1", features = ["mint"] }

[target.'cfg(target_family = "windows")'.dependencies]
openxr = { version = "0.17.1", features = ["mint", "static"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
ash = { version = "0.37.3", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2.91"
web-sys = { version = "0.3.68", features = [
    # STANDARD
    'console',
    'Document',
    'Element',
    'Headers',
    'Navigator',
    'Window',
    # IO
    # 'Url',
    # WEBGL
    'Gpu',
    'HtmlCanvasElement',
    'WebGl2RenderingContext',
    'WebGlFramebuffer',
    'GamepadHapticActuator',
    ## XR
    'DomPointReadOnly',
    'XrWebGlLayer',
    'XrBoundedReferenceSpace',
    'XrEye',
    'XrFrame',
    'XrHandedness',
    'XrInputSource',
    'XrInputSourceArray',
    'XrInputSourceEvent',
    'XrInputSourceEventInit',
    'XrInputSourcesChangeEvent',
    'XrJointPose',
    'XrJointSpace',
    'XrPose',
    'XrReferenceSpace',
    'XrReferenceSpaceEvent',
    'XrReferenceSpaceEventInit',
    'XrReferenceSpaceType',
    'XrRenderState',
    'XrRenderStateInit',
    'XrRigidTransform',
    'XrSession',
    'XrSessionEvent',
    'XrSessionEventInit',
    'XrSessionInit',
    'XrSessionMode',
    'XrSpace',
    'XrTargetRayMode',
    'XrView',
    'XrViewerPose',
    'XrViewport',
    'XrVisibilityState',
    'XrWebGlLayer',
    'XrWebGlLayerInit',
    'XrSystem',
] }
wasm-bindgen-futures = "0.4"

[workspace]
members = ["xr_api"]
