[package]
name = "bevy_openxr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ash = "0.37.3"
bevy = { git = "https://github.com/awtterpip/bevy", default-features = false, features = ["bevy_render"] }
openxr = { version = "0.17.1" }
wgpu = "0.16.0"
wgpu-core = { version = "0.16.0", features = ["vulkan"] }
wgpu-hal = "0.16.0"

[dev-dependencies]
bevy = { git = "https://github.com/awtterpip/bevy" }
color-eyre = "0.6.2"

[[example]]
name = "xr"
path = "examples/xr.rs"
