[package]
name = "bevy_openxr"
version = "0.1.0"
edition = "2021"

[features]
default = ["openxr/mint", "linked"]
linked = ["openxr/linked"]

[dependencies]
anyhow = "1.0.75"
ash = "0.37.3"
bevy = "0.12"
mint = "0.5.9"
wgpu = "0.17.1"
wgpu-core = { version = "0.17.1", features = ["vulkan"] }
wgpu-hal = "0.17.1"

[target.'cfg( target_family = "unix" )'.dependencies]
openxr = "0.17.1"

[target.'cfg(not(target_family = "unix"))'.dependencies]
openxr = { version = "0.17.1", features = ["static"] }

[dev-dependencies]
bevy = "0.12"
color-eyre = "0.6.2"

[[example]]
name = "xr"
path = "examples/xr.rs"

[profile.release]
debug = true
