[package]
name = "bevy_openxr"
version = "0.1.0"
edition = "2021"

[features]
default = ["openxr/mint"]

[dependencies]
anyhow = "1.0.75"
ash = "0.37.3"
bevy = "0.12"
mint = "0.5.9"
wgpu = "0.17.1"
wgpu-core = { version = "0.17.1", features = ["vulkan"] }
wgpu-hal = "0.17.1"

[target.'cfg( target_os = "linux" )'.dependencies]
openxr = { version = "0.17.1", features = ["linked"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
openxr = { version = "0.17.1", features = ["linked", "static"] }

[dev-dependencies]
bevy = "0.12"
color-eyre = "0.6.2"

[[example]]
name = "xr"
path = "examples/xr.rs"

[profile.release]
debug = true
