[package]
name = "bevy_openxr"
version = "0.1.0"
edition = "2021"

[features]
default = ["linked"]
linked = ["openxr/linked", "openxr/static"]

[dependencies]
anyhow = "1.0.75"
ash = "0.37.3"
bevy = { git = "https://github.com/bevyengine/bevy.git" }
openxr = { version = "0.17.1", features = ["mint"] }
mint = "0.5.9"
wgpu = "0.16.0"
wgpu-core = { version = "0.16.0", features = ["vulkan"] }
wgpu-hal = "0.16.0"

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
color-eyre = "0.6.2"

[[example]]
name = "xr"
path = "examples/xr.rs"

[profile.release]
debug = true
