[package]
name = "demo"
version = "0.1.0"
description = "Demo using bevy_oxr"
edition.workspace = true
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
bevy.workspace = true
bevy_oxr.path = "../../"
bevy_rapier3d = "0.25"
color-eyre.workspace = true
