[package]
name = "demo"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
# bevy = "0.11.3"
bevy_openxr = { git = "file:///home/schmarni/Code/adeptus_bevy_oxr", default-features = false}
bevy_rapier3d = { git = "https://github.com/Schmarni-Dev/bevy_rapier" }
color-eyre = "0.6.2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

